name = IR-Love Custom Layout
description = A simple layout demonstrating mobile first and Susy.
preview = preview.png
template = ir_love-layout

; Regions
regions[top_navigation]	= Top Navigation
regions[branding]       = Branding
regions[header]         = Header
;regions[navigation]    = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/ir_love/ir_love.layout.css
