name = Inno Love
description = A simple layout demonstrating mobile first and Susy.
preview = preview.png
template = inno_love-layout

; Regions
regions[branding]       = Branding
regions[top_navigation]	= Top Navigation
regions[header]         = Header
;regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/inno_love/inno_love.layout.css
